import { HeartPulse } from 'lucide-react';
import type { CustomerHealth, CustomerRetentionSummary } from '../../types/customer';

interface CustomerRetentionCardProps { readonly retention: CustomerRetentionSummary; readonly health: CustomerHealth }
const TONES = { healthy: 'text-emerald-300 bg-emerald-500/10', attention: 'text-amber-300 bg-amber-500/10', critical: 'text-red-300 bg-red-500/10' } as const;

export function CustomerRetentionCard({ retention, health }: CustomerRetentionCardProps) {
  return <article className="rounded-2xl border border-slate-800 bg-slate-900/70 p-5" aria-labelledby="customer-retention-title"><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-rose-500/10 text-rose-400"><HeartPulse className="h-5 w-5" aria-hidden="true" /></div><div><h3 id="customer-retention-title" className="text-base font-black text-white">Customer retention</h3><p className="text-[11px] text-slate-500">30% repeat rate and 1.5 orders are documented healthy thresholds</p></div></div><span className={`mt-5 inline-flex rounded-full px-3 py-1 text-xs font-black uppercase tracking-wider ${TONES[health.status]}`}>{health.label}</span><ul className="mt-3 space-y-1 text-xs leading-relaxed text-slate-400">{health.reasons.map((reason) => <li key={reason}>• {reason}</li>)}</ul><div className="mt-5 grid grid-cols-1 gap-3 sm:grid-cols-2">{[retention.current, retention.previous].map((period) => <div key={period.label} className="rounded-xl border border-slate-800 bg-slate-950/40 p-3"><p className="text-[10px] font-black uppercase tracking-wider text-slate-500">{period.label}</p><p className="mt-1 text-[10px] text-slate-600">{period.startDate} — {period.endDate}</p><p className="mt-3 text-xl font-black text-white">{period.retentionRate === null ? 'Unavailable' : `${period.retentionRate.toFixed(1)}%`}</p><p className="mt-1 text-[11px] text-slate-500">{period.retainedCustomers} retained of {period.activeCustomers} active purchasers</p></div>)}</div><p className="mt-4 text-xs text-slate-400">Trend: <span className="font-black capitalize text-white">{retention.trend}</span>{retention.percentagePointChange !== null ? ` · ${Math.abs(retention.percentagePointChange).toFixed(1)} percentage points` : ''}</p></article>;
}
