import { BadgeDollarSign } from 'lucide-react';
import type { CustomerMetrics } from '../../types/customer';

interface CustomerLifetimeValueCardProps { readonly metrics: CustomerMetrics }
const currency = (value: number) => `LKR ${Math.round(value).toLocaleString()}`;

export function CustomerLifetimeValueCard({ metrics }: CustomerLifetimeValueCardProps) {
  return <article className="rounded-2xl border border-slate-800 bg-slate-900/70 p-5" aria-labelledby="customer-lifetime-title"><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-emerald-500/10 text-emerald-400"><BadgeDollarSign className="h-5 w-5" aria-hidden="true" /></div><div><h3 id="customer-lifetime-title" className="text-base font-black text-white">Customer lifetime value</h3><p className="text-[11px] text-slate-500">Non-cancelled orders only</p></div></div>{metrics.averageCustomerLifetimeValue === null ? <p className="mt-5 rounded-xl border border-dashed border-slate-700 p-4 text-xs text-slate-500">No usable customer purchase history is available.</p> : <div className="mt-5 grid grid-cols-2 gap-3"><div className="rounded-xl bg-slate-950/50 p-3"><p className="text-[10px] uppercase tracking-wider text-slate-500">Average lifetime value</p><p className="mt-1 text-xl font-black text-white">{currency(metrics.averageCustomerLifetimeValue)}</p></div><div className="rounded-xl bg-slate-950/50 p-3"><p className="text-[10px] uppercase tracking-wider text-slate-500">Average orders</p><p className="mt-1 text-xl font-black text-white">{metrics.averageOrdersPerCustomer?.toFixed(2)}</p></div><div className="col-span-2 rounded-xl border border-slate-800 px-3 py-2.5 text-xs text-slate-500">{metrics.activePurchasingCustomers} active purchasing customers · {metrics.returningCustomers} repeat customers ({metrics.repeatPurchaseRate.toFixed(1)}%)</div></div>}{metrics.excludedOrderCount > 0 && <p className="mt-4 text-[11px] text-amber-400">{metrics.excludedOrderCount} non-cancelled orders lacked a usable transient grouping key and were excluded.</p>}</article>;
}
