import { ChartNoAxesColumnIncreasing } from 'lucide-react';
import type { PriceDistribution } from '../../types/pricing';

interface PriceDistributionCardProps { readonly prices: PriceDistribution }
const currency = (value: number) => `LKR ${Math.round(value).toLocaleString()}`;

export function PriceDistributionCard({ prices }: PriceDistributionCardProps) {
  const rankings = [{ title: 'Highest priced active products', items: prices.highestPricedProducts }, { title: 'Lowest priced active products', items: prices.lowestPricedProducts }];
  return <article className="rounded-2xl border border-slate-800 bg-slate-900/70 p-5" aria-labelledby="price-distribution-title"><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-blue-500/10 text-blue-400"><ChartNoAxesColumnIncreasing className="h-5 w-5" aria-hidden="true" /></div><h3 id="price-distribution-title" className="text-base font-black text-white">Selling-price distribution</h3></div>{prices.averageSellingPrice === null ? <p className="mt-5 rounded-xl border border-dashed border-slate-700 p-4 text-xs text-slate-500">No valid active-product selling prices are available.</p> : <><div className="mt-5 grid grid-cols-2 gap-3"><div className="rounded-xl bg-slate-950/50 p-3"><p className="text-[10px] uppercase tracking-wider text-slate-500">Average</p><p className="mt-1 text-lg font-black text-white">{currency(prices.averageSellingPrice)}</p></div><div className="rounded-xl bg-slate-950/50 p-3"><p className="text-[10px] uppercase tracking-wider text-slate-500">Median</p><p className="mt-1 text-lg font-black text-white">{currency(prices.medianSellingPrice || 0)}</p></div></div><div className="mt-5 grid gap-5 xl:grid-cols-2">{rankings.map((ranking) => <div key={ranking.title}><h4 className="text-[10px] font-black uppercase tracking-wider text-slate-500">{ranking.title}</h4><ol className="mt-2 space-y-2">{ranking.items.map((product) => <li key={product.id} className="flex justify-between gap-4 rounded-xl border border-slate-800 px-3 py-2.5 text-xs"><span className="truncate font-bold text-slate-300">{product.name}</span><span className="shrink-0 font-black text-white">{currency(product.sellingPrice)}</span></li>)}</ol></div>)}</div></>}</article>;
}
