import { ShieldCheck } from 'lucide-react';
import type { PricingHealth, PricingIssueSummary, PricingProductIssue } from '../../types/pricing';

interface PricingHealthCardProps { readonly health: PricingHealth; readonly invalid: readonly PricingIssueSummary[]; readonly consistency: readonly PricingIssueSummary[]; readonly products: readonly PricingProductIssue[] }
const TONES = { healthy: 'text-emerald-300 bg-emerald-500/10', attention: 'text-amber-300 bg-amber-500/10', critical: 'text-red-300 bg-red-500/10', unavailable: 'text-slate-300 bg-slate-500/10' } as const;

export function PricingHealthCard({ health, invalid, consistency, products }: PricingHealthCardProps) {
  const issues = [...invalid, ...consistency].filter((item) => item.count > 0);
  return <article className="rounded-2xl border border-slate-800 bg-slate-900/70 p-5" aria-labelledby="pricing-health-title"><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-emerald-500/10 text-emerald-400"><ShieldCheck className="h-5 w-5" aria-hidden="true" /></div><div><h3 id="pricing-health-title" className="text-base font-black text-white">Price consistency summary</h3><p className="text-[11px] text-slate-500">20% discount coverage is the documented healthy threshold</p></div></div><span className={`mt-5 inline-flex rounded-full px-3 py-1 text-xs font-black uppercase tracking-wider ${TONES[health.status]}`}>{health.label}</span><ul className="mt-3 space-y-1.5 text-xs leading-relaxed text-slate-400">{health.reasons.map((reason) => <li key={reason}>• {reason}</li>)}</ul>{issues.length > 0 && <div className="mt-5 grid grid-cols-1 gap-2 sm:grid-cols-2">{issues.map((issue) => <div key={issue.category} className="flex items-center justify-between gap-3 rounded-xl border border-slate-800 px-3 py-2 text-[11px]"><span className="text-slate-500">{issue.label}</span><span className="font-black text-white">{issue.count}</span></div>)}</div>}{products.length > 0 && <div className="mt-5 border-t border-slate-800 pt-4"><h4 className="text-[10px] font-black uppercase tracking-wider text-slate-500">Affected products</h4><ul className="mt-2 space-y-2">{products.map((product) => <li key={product.id} className="rounded-xl bg-slate-950/50 px-3 py-2.5"><p className="text-xs font-bold text-slate-300">{product.name}</p><p className="mt-1 text-[10px] leading-relaxed text-slate-500">{product.categories.map((category) => category.replaceAll('-', ' ')).join(' · ')}</p></li>)}</ul></div>}</article>;
}
