export interface RawA2ZProduct {
  sku: string;
  title: string;
  longDescription: string;
  mediaGallery: string[];
  wholesalePrice: number;
  recommendedRetailPrice: number;
  inventoryLevel: number;
  supplierProductId?: string;
  barcode?: string;
  shortDescription?: string;
  brand?: string;
  manufacturer?: string;
  model?: string;
  categoryHierarchy?: string[];
  supplierCategory?: string;
  supplierSubcategory?: string;
  tags?: string[];
  keywords?: string[];
  productType?: string;
  collection?: string;
  attributes?: Record<string, unknown>;
  variants?: unknown[];
  options?: unknown;
  specifications?: Record<string, string>;
  features?: string[];
  dimensions?: unknown;
  weight?: unknown;
  packageSize?: unknown;
  shippingClass?: string;
  warranty?: unknown;
  countryOfOrigin?: string;
  videoUrls?: string[];
  price?: number;
  comparePrice?: number;
  costPrice?: number;
  currency?: string;
  tax?: unknown;
  discount?: number;
  availability?: string;
  leadTime?: unknown;
  minimumOrderQuantity?: number;
  maximumOrderQuantity?: number;
  visibility?: unknown;
  status?: string;
  lastUpdated?: string;
  createdDate?: string;
  slug?: string;
  metaDescription?: string;
  extraAttributes?: Record<string, unknown>;
  providedFields?: string[];
}
